language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

script:
  - make

after_success:
  - curl https://learning-on-chip.github.io/travis/documentation.sh | bash

env:
  global:
    - secure: eYNp9X3MEhIHcTfJ7xPyTYyNLhh2ZJnaz1ft5MsXnSW++Ihv1U7xBzBj2Y0dMTcKNbV/1teQiq9YNGQWEc/DoT+c7VfKTUPozaplpse8xvpAZ8YSt7dIqODlu2ccNkl3C4bCZYXONUrSIg4dyNWCXLWbCKPdS/J/SH0bcxvL9FSVM1pjg3Z6ozVP1QeGBLPYfdzJtPByDHVMrqtIrBoTqN++O3WYeDdmMqZbZhvTsEZOQ2cB7wnfG8IE9UXe0gv4CprhK4RDiB7iwpYp774E1as2aGXoE5t6pEYmfrBF7quLFqa4NTN9BCUvjqfV03QEoWmqYRoIXy2rfdtv5W1ci07bm0qe7nKJp1c31X/IkEVt5nf8C3sLJFxygCCMdAoYhR9nq0TjT8S+m5eHlgylc+DPjvVLbe6brgQ7NNkZniMI0nv37NJDmsS1329fyXB1U1G7n9ngvZRVdWlgJan0JgNskrRKNE/rjMMt9cjMKbZ+S9k8eX7lqVrXJB9zaJBz1o3CJxUx4h5QjRCphGE5ZlBOfqjBP7yEkJVox2udqUS+P7yts4f+7Pzem4OGezBhC7cpzrXtWR8FwcMDvq5jpakJQGSOM3EW8AK3B0zOF2dClneKk2P7oid0Wh2vS5s7vYU6k/6KRieis1Ri4p5y7QilFd6yl+Om2lJ3d1WirGk=

notifications:
  email: false
